kind: pipeline
name: build

  - name: hello:
    image: alpine
    access_token: placeholder
    commands: 
      - echo $PLUGIN_ACCESS_TOKEN
      
  - name: archive
    image: nexus.admin.sharecare.com/drone-build-plugin
    settings:
      version: "1.0.0"
      namespace: qa
