kind: pipeline
name: build

  - name: docker
    image: nexus.admin.sharecare.com/drone-nexus-docker
    settings:
      version: "1.0.0"
      
  - name: archive
    image: nexus.admin.sharecare.com/drone-build-plugin
    settings:
      version: "1.0.0"
      namespace: qa
